import type { Metadata } from "next";
import { notFound, redirect } from "next/navigation";
import { requireUser } from "@/lib/auth/rbac";
import { db } from "@/lib/db/client";
import { getProjectedReport } from "@/services/reports/project-report";
import type { ScoreBasis } from "@/services/reports/evaluate-report";
import type { ReportSnapshotPayload } from "@/services/reports/snapshot";
import { PrintReport } from "./print-report";
import type { UserPlan } from "@prisma/client";

export const metadata: Metadata = { title: "Report PDF" };
export const dynamic = "force-dynamic";

/**
 * Print-optimised report — the "Downloadable PDF" the pricing page sells.
 *
 * Rendered server-side through the SAME ownership check and plan projection as
 * the interactive report, so a PDF can never contain content its viewer is not
 * entitled to: locked premium checks are already stripped before serialization
 * and simply are not in the data this page receives.
 *
 * The document is generated by the browser's own print-to-PDF. That keeps the
 * output pixel-identical to the report design, costs no server render, and
 * adds no dependency — the alternative (hand-laying the report out in a PDF
 * library) is more code and worse output.
 */
export default async function ReportPdfPage({
  params,
}: {
  params: Promise<{ reportId: string }>;
}) {
  const user = await requireUser();
  const { reportId: publicId } = await params;

  const report = await db.report.findUnique({
    where: { publicId },
    include: { website: { select: { domain: true, url: true } } },
  });
  if (!report || report.deletedAt) notFound();
  if (report.userId !== user.id && user.role !== "MASTER_ADMIN") notFound();

  // PDF export is a Premium feature (pricing table). Admins get it for support.
  if (user.plan !== "PREMIUM" && user.role !== "MASTER_ADMIN") {
    redirect(`/dashboard/reports/${publicId}?upgrade=pdf`);
  }

  const [projected, snapshot] = await Promise.all([
    getProjectedReport(report.id, user.plan as UserPlan),
    db.reportSnapshot.findUnique({
      where: { reportId: report.id },
      select: { scoreBasis: true, payload: true },
    }),
  ]);
  if (!projected) {
    redirect(`/dashboard/reports/${publicId}`);
  }

  const site =
    (snapshot?.payload as unknown as ReportSnapshotPayload | null)?.site ?? null;

  return (
    <PrintReport
      publicId={publicId}
      domain={report.website.domain}
      url={report.website.url}
      overallScore={report.overallScore}
      grade={report.grade}
      status={report.status}
      passedCount={report.passedCount}
      failedCount={report.failedCount}
      warningCount={report.warningCount}
      criticalIssueCount={report.criticalIssueCount}
      auditedAt={(report.completedAt ?? report.createdAt).toISOString()}
      platform={site?.platform ?? null}
      themeName={site?.themeName ?? null}
      appCount={site?.isShopify ? site.appCount : null}
      scoreBasis={(snapshot?.scoreBasis as ScoreBasis | null) ?? null}
      projected={projected}
    />
  );
}
