import type { Metadata } from "next";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { Lock, CheckCircle2, ArrowRight } from "lucide-react";
import { db } from "@/lib/db/client";
import { getReportForViewer } from "@/services/reports/access";

export const metadata: Metadata = { title: "Your website audit" };
export const dynamic = "force-dynamic";

/**
 * Public report gate.
 * - Anonymous owner: score teaser + blurred/locked sections + signup CTA.
 *   Section details are never sent to the client — the "blur" is real absence.
 * - Authenticated owner: placeholder link into the dashboard (full report UI
 *   is Phase 7; report content itself is generated by the Phase 4/6 engine).
 */
export default async function ReportGatePage({
  params,
}: {
  params: Promise<{ publicId: string }>;
}) {
  const { publicId } = await params;

  const access = await getReportForViewer(publicId);
  if (!access.ok) notFound();

  const { report, viewer } = access;

  if (report.status === "QUEUED" || report.status === "PROCESSING") {
    redirect(`/analyze/${publicId}`);
  }

  const website = await db.website.findUnique({
    where: { id: report.websiteId },
    select: { domain: true },
  });
  const domain = website?.domain ?? "your website";

  // Authenticated owners go to the dashboard report view (Phase 7)
  if (viewer === "owner-user" || viewer === "admin") {
    return (
      <main className="flex min-h-screen flex-col items-center justify-center px-4">
        <div className="card w-full max-w-md p-8 text-center">
          <CheckCircle2 className="mx-auto h-10 w-10 text-success-600" aria-hidden />
          <h1 className="mt-4 text-xl font-bold text-ink">Audit complete</h1>
          <p className="mt-2 text-sm text-ink-secondary">
            Your report for <strong>{domain}</strong> is saved to your account.
          </p>
          {report.overallScore !== null && (
            <div className="mx-auto mt-6 flex h-24 w-24 items-center justify-center rounded-full border-8 border-brand-600 text-3xl font-bold text-ink">
              {Math.round(report.overallScore)}
            </div>
          )}
          <p className="mt-6 text-xs text-ink-muted">
            The full report view arrives in Phase 7 of the build.
          </p>
          <Link
            href="/dashboard"
            className="mt-4 inline-flex items-center gap-1.5 rounded-lg bg-brand-600 px-5 py-2.5 text-sm font-medium text-white hover:bg-brand-700"
          >
            Go to dashboard
            <ArrowRight className="h-4 w-4" aria-hidden />
          </Link>
        </div>
      </main>
    );
  }

  // Anonymous owner: locked preview + conversion CTA
  const teaserSections = [
    "Page Speed",
    "SEO",
    "Technical SEO",
    "Accessibility",
    "Mobile Usability",
    "Security",
  ];

  return (
    <main className="flex min-h-screen flex-col items-center px-4 py-12">
      <div className="w-full max-w-lg">
        <div className="text-center">
          <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-brand-600 text-xl font-bold text-white">
            A
          </div>
          <h1 className="mt-5 text-2xl font-bold tracking-tight text-ink">
            Your website audit is ready
          </h1>
          <p className="mt-2 text-sm text-ink-secondary">
            Create a free account or sign in to view your report for{" "}
            <strong>{domain}</strong>.
          </p>
        </div>

        {/* Score teaser */}
        {report.overallScore !== null && (
          <div className="card mt-8 flex items-center justify-between p-6">
            <div>
              <div className="text-sm font-medium text-ink">Overall score</div>
              <div className="text-xs text-ink-muted">
                {report.grade ?? "See the full breakdown inside"}
              </div>
            </div>
            <div className="flex h-20 w-20 items-center justify-center rounded-full border-[6px] border-brand-600 text-2xl font-bold text-ink">
              {Math.round(report.overallScore)}
            </div>
          </div>
        )}

        {/* Locked sections — titles only; details never leave the server */}
        <div className="card mt-4 divide-y divide-slate-100 overflow-hidden">
          {teaserSections.map((name) => (
            <div key={name} className="flex items-center gap-3 px-5 py-4">
              <Lock className="h-4 w-4 shrink-0 text-ink-muted" aria-hidden />
              <div className="min-w-0 flex-1">
                <div className="text-sm font-medium text-ink">{name}</div>
                <div
                  className="mt-1.5 h-2.5 w-3/4 rounded bg-slate-200 blur-[2px]"
                  aria-hidden
                />
              </div>
              <span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs text-ink-muted">
                Locked
              </span>
            </div>
          ))}
        </div>

        <div className="mt-8 flex flex-col gap-3 sm:flex-row">
          <Link
            href="/signup"
            className="flex-1 rounded-lg bg-brand-600 px-5 py-3 text-center text-sm font-semibold text-white transition-colors hover:bg-brand-700"
          >
            Create free account
          </Link>
          <Link
            href="/login"
            className="flex-1 rounded-lg border border-slate-300 bg-white px-5 py-3 text-center text-sm font-semibold text-ink transition-colors hover:bg-slate-50"
          >
            Sign in
          </Link>
        </div>
        <p className="mt-4 text-center text-xs text-ink-muted">
          Your report attaches to your account automatically — no need to run the audit
          again.
        </p>
      </div>
    </main>
  );
}
